apiVersion: apps/v1
kind: Deployment
metadata:
  name: ow-agent
  labels:
    app: ow-agent
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ow-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ow-agent
    spec:
      serviceAccountName: ow-agent
      containers:
      - env:
        - name: REDIS_HOST
          value: redis.default.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: THIS
          value: http://ow-agent.default.svc.cluster.local:8000/
#        - name: OPENFAAS_ADMIN
#          value: "admin"
#        - name: OPENFAAS_PASSWORD
#          value: 176Js81K6bsEb20C58nOnjyUH
#        - name: JWT_KEY
#          value : 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        - name: JWT_ALGORITHM
          value: HS256
        - name: JWT_EXPIRE_MINUTES
          value: "30"
        image: gabrielemorabito/ow-agent
        imagePullPolicy: Always
        name: agent
        ports:
        - containerPort: 8000
          name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ow-agent
  labels:
    app: ow-agent