apiVersion: apps/v1
kind: Deployment
metadata:
  name: ow-agent
  labels:
    app: ow-agent
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ow-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ow-agent
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis.default.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: THIS
          value: http://ow-agent.default.svc.cluster.local:8000/
        image: gabrielemorabito/ow-agent
        imagePullPolicy: Always
        name: agent
        ports:
        - containerPort: 8000
          name: http
