apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: group2-network-policy
  namespace: group2
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openfaas
        - namespaceSelector:
            matchLabels:
              scope: group2
        - namespaceSelector:
            matchLabels:
              scope: user2
        - namespaceSelector:
            matchLabels:
              scope: user3
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
        - namespaceSelector:
            matchLabels:
              app: nginx

