apiVersion: v1
kind: ConfigMap
metadata:
  name: confnginx
  namespace: proxy-user3
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen 8080;

        server_name gateway.openfaas.svc.cluster.local;
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location /healthz {
          return 200;
        }

        location ~* .user3 {
          proxy_pass http://gateway.openfaas.svc.cluster.local:8080$1;
        }

        location ~* .group1 {
          proxy_pass http://gateway.openfaas.svc.cluster.local:8080$1;
        }

        location ~* .group2 {
          proxy_pass http://gateway.openfaas.svc.cluster.local:8080$1;
        }
      }
    }